trigger:
  branches:
    include:
      - main

variables:
  dotnetVersion: '10.0.x'
  imageName: 'dougdesk/taskflow-api'

stages:

# ─── STAGE 1: CI ──────────────────────────────────────────
- stage: CI
  displayName: 'Build e Testes'
  jobs:
  - job: Build
    displayName: 'Compilar e Testar'
    pool:
      name: 'Default'

    steps:
    - task: UseDotNet@2
      displayName: 'Instalar .NET 10'
      inputs:
        version: $(dotnetVersion)
        includePreviewVersions: true

    - script: dotnet restore src/TaskFlow.API/TaskFlow.API.csproj
      displayName: 'Restore'

    - script: dotnet build src/TaskFlow.API/TaskFlow.API.csproj -c Release --no-restore
      displayName: 'Build'

    - script: dotnet test tests/TaskFlow.Tests/TaskFlow.Tests.csproj --no-restore --logger trx
      displayName: 'Testes'

    - task: PublishTestResults@2
      displayName: 'Publicar Resultados dos Testes'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
      condition: always()
      
# ─── STAGE 2: CD ──────────────────────────────────────────
- stage: CD
  displayName: 'Build e Push Docker'
  dependsOn: CI
  condition: succeeded()
  jobs:
  - job: Docker
    displayName: 'Build e Push Imagem'
    pool:
      name: 'Default'
    steps:
    - task: Docker@2
      displayName: 'Build e Push'
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile.api'
        tags: |
          latest
          $(Build.BuildId)          
    - script: |
        docker compose -f $(Build.SourcesDirectory)/docker-compose.yml pull
        docker compose -f $(Build.SourcesDirectory)/docker-compose.yml up -d
    
    displayName: 'Deploy — Docker Compose'