trigger:
  branches:
    include:
      - main

variables:
  dotnetVersion: '10.0.x'

stages:

# ─── STAGE 1: CI ──────────────────────────────────────────
- stage: CI
  displayName: 'Build e Testes'
  jobs:
  - job: Build
    displayName: 'Compilar e Testar'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseDotNet@2
      displayName: 'Instalar .NET 10'
      inputs:
        version: $(dotnetVersion)
        includePreviewVersions: true

    - script: dotnet restore src/TaskFlow.API/TaskFlow.API.csproj
      displayName: 'Restore'

    - script: dotnet build src/TaskFlow.API/TaskFlow.API.csproj -c Release --no-restore
      displayName: 'Build'

    - script: dotnet test tests/TaskFlow.Tests/TaskFlow.Tests.csproj --no-restore --logger trx
      displayName: 'Testes'

    - task: PublishTestResults@2
      displayName: 'Publicar Resultados dos Testes'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
      condition: always()