apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__DefaultConnection: "Data Source=/data/taskflow.db"
  Cors__Origins: "http://localhost:30080"